User/marcelo li gonzales/recruit training
UCSolarCarTeam/Development-Resources pull request #160
Opened 2020-10-27 00:27 UTC by MarceloLiGonzales

Request to review Basic Training

2020-10-27 02:15 UTC, duan-le requested changes

2020-10-27 02:15 UTC, duan-le commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +    cout << "Predicted value of p: 0xsomething" /* << PLACE YOUR PREDICTION HERE*/ << endl;
You can remove the comment  `/* << PLACE YOUR PREDICTION HERE*/`. Do the same to all the other lines that this applies to.

2020-10-27 02:28 UTC, duan-le requested changes

2020-10-27 02:28 UTC, duan-le commented on Recruit-Training/Basic-Recruit-Training/person/main.cpp
>  // Pass a and b into mySwap
Call the respective functions here.

2020-10-27 02:29 UTC, duan-le requested changes

2020-10-27 02:29 UTC, duan-le commented on Recruit-Training/Basic-Recruit-Training/person/main.cpp
>  // Pass in a to myIncrement
Call this one too.

2020-10-29 18:14 UTC, JessieG123 requested changes

2020-10-29 18:14 UTC, JessieG123 commented on Recruit-Training/Basic-Recruit-Training/person/Person.h
> +#include <iostream>
Why are you adding this? From the instructions, you are not permitted to modify anything in `Person.h`

2020-10-29 18:14 UTC, JessieG123 commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +    cout << "Predicted value of p: 0xsomething" << endl;
As mentioned in the instructions, please place your predicted values between `<< <<`.

2020-10-29 18:14 UTC, JessieG123 commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +void MySwap(int *a, int *b)
First letter should not be capitalized.

2020-10-29 18:29 UTC, JessieG123 requested changes
As mentioned in the instructions, you are to create a `Person.cpp` file. Please ensure you read the instructions properly.

2020-10-30 03:33 UTC, duan-le approved these changes
Everything looks good to me. Please **DO NOT** merge this branch into `master`. Get an approval from another reviewer and then you can close this PR.

2020-10-31 16:13 UTC, JessieG123 approved these changes
Looks good! Please **do not** merge instead just close the PR. If you need help please let us know.

2020-10-31 16:13 UTC, closed without merging