Basic Recruit Training Finished
UCSolarCarTeam/Development-Resources pull request #164
Opened 2020-10-30 03:05 UTC by bcayanan

2020-10-30 03:17 UTC, JessieG123 requested changes
Please add a description to the PR. 
~~I think you also need to config email and username since your profile icon doesn't show up with your commit.~~ JK I see it now.

2020-10-30 23:12 UTC, JessieG123 requested changes

2020-10-30 23:12 UTC, JessieG123 commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +using namespace::std;
Not sure if you can do that.... but either way if you're going to use it do it like `using namespace std`. Also it is bad practice to use it in general so I wouldn't recommending using it.

2020-10-30 23:12 UTC, JessieG123 commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +    {
Consistent indentation please.

2020-11-01 18:02 UTC, duan-le approved these changes
Everything looks good to me. Please **DO NOT** merge this branch into `master`. Get an approval from another reviewer and then you can close this PR.

2020-11-01 18:12 UTC, JessieG123 approved these changes
Looks great! Awesome job Bryce! Now, **do not** merge the PR, instead close it. 
Let us know if you have any questions!

2020-11-01 18:57 UTC, closed without merging