Telemetry Teaser
UCSolarCarTeam/Development-Resources pull request #180
Opened 2020-11-28 20:33 UTC by Dillonsd

Telemetry teaser complete.
Not sure if that's how you want the button to display the calculated range.

2020-11-28 22:36 UTC, JaydenBischoff requested changes
Currently when the webapp loads, the errors stating that the speed and battery percentage are required are shown. Could you please change this so the errors do not show until:
-  the user clicks the field and if the user clicks outside of the field without entering any number the error for that field is displayed or,
-  the user clicks the calculate button without clicking on the field

2020-11-28 22:36 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +      (4 * this.battery) + this.weather;
This can all go on one line

2020-11-28 22:36 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +    this.range + " km.";
This can all go on one line

2020-11-28 22:36 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +        <label *ngIf="speedInput.errors.required" [ngClass] = "'error'">Speed is required</label>
It is convention to have no spaces between operators in our html files. So [ngClass] = "'error'" can be [ngClass]="'error'"
Please implement this change to all similar cases in the html file

2020-11-28 22:36 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +        <label *ngIf="batteryInput.errors.required" [ngClass] = "'error'">Battery is required</label>
Instead of the error label saying 'Battery is required', can the label say 'Battery percentage is required'

2020-12-03 23:29 UTC, Dillonsd commented
Made the changes requested. Error messages now only show up after text fields have been clicked on, or if the button was pressed and either of the fields weren't filled.

2020-12-05 17:58 UTC, JensVarughese requested changes

2020-12-05 17:58 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +      if(this.battery == -1){
Add a space between the curly brace

2020-12-05 17:58 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +    if(this.speed == -1){
Add a space between the curly brace

2020-12-05 17:58 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +  rangeForm:FormGroup
missing semicolon

2020-12-05 17:58 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +export class AppComponent implements OnInit{
Add a space between the curly brace and OnInit

2020-12-05 18:31 UTC, Dillonsd commented
Made the code style changes with the curly braces and added the missing semi colon

2020-12-05 18:35 UTC, JensVarughese approved these changes
Looks good from what I can see. I dont think you need to make another commit for that small change. Just keep it in mind if you join Telemetry.

2020-12-05 18:35 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +    this.rangeForm = new FormGroup( {
U dont need to add a space between the curly brace here

2020-12-05 18:37 UTC, JaydenBischoff approved these changes
Great work! Please close the branch instead of merging it.

2020-12-05 19:02 UTC, closed without merging