Telemetry Teaser Done
UCSolarCarTeam/Development-Resources pull request #183
Opened 2021-01-05 23:38 UTC by Ahmed-I-Abdullah

2021-01-16 22:58 UTC, JaydenBischoff requested changes
It looks really good so far. Right now, an error message will show while the user is typing if the input does not meet the requirements but the input field stay white. It changes colour only once the user clicks outside of field. Can you change this so that the input fields change colour while the user is typing? 

Also, the error messages that appear for speed and battery percentage are not centered on the page. Can you fix this so that the error messages are centered like the other titles on the page.

2021-01-16 22:58 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +	this.result = "The predicted range of the Eylsia is " + this.range + " km.";
You can indent the contents of this function with 2 spaces to match your other functions.

2021-01-16 22:58 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +} from "@angular/forms";
This can all be on a single line and the comma following Validators can be removed.

2021-01-16 22:58 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +import { Component, OnInit } from '@angular/core'
Missing semicolon at the end of the line.

2021-01-22 02:01 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +	  }" name="speed" type="number" formControlName="inputSpeed" placeholder="Speed" (keyup)="onKeySpeed($event)" >
Lines 8-10 should have an indent, so it is easier to tell that it is part of the input field.

2021-01-22 02:16 UTC, JensVarughese requested changes
Looks good so far. Just fix the changes Jayden and I requested.

2021-01-22 02:52 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +	(keyup)="onKeyBattery($event)" >
Sorry I meant lines 27-28 were supposed to be on the same line. The comment just made it look like two lines.

2021-01-22 02:59 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +	(keyup)="onKeyBattery($event)" >
Also these lines are supposed to be indented, not spaced, I just added spaces for the comment . So it should look something like this:

![image](https://user-images.githubusercontent.com/29678619/105439935-fab8f180-5c22-11eb-9d52-a6d35955f585.png)

2021-01-22 03:02 UTC, JensVarughese requested changes
One thing I have noticed is that when you click "Calculate" before typing any values in or clicking the input fields, nothing happens. The errors should still show up in this case.

2021-02-06 20:28 UTC, closed without merging