Finished Viscomm Recruit Training
UCSolarCarTeam/Development-Resources pull request #192
Opened 2021-02-16 17:37 UTC by Ahmed-I-Abdullah

2021-02-26 02:17 UTC, DatLam25 commented on Recruit-Training/Viscomm-Recruit-Training/src/BatteryStateDisplayService.cpp
> +                        << " Time Till Charged or Depleted: " << batteryStateOfChargeService_.timeWhenChargedOrDepleted().toString() << endl;
Time should be printed out as HH:MM:SS.ZZZ.

2021-02-26 02:20 UTC, DatLam25 commented on Recruit-Training/Viscomm-Recruit-Training/src/BatteryStateOfChargeService.cpp
> +    double timeDifference = pastData_->time.QTime::msecsTo(currentData_->time) / 3600000.0;
All instances of `3600000.0` should be replaced with a constant so we can know that the number means.

2021-02-27 17:19 UTC, Hesham-E reviewed
Hey this looks great to me! You've got the hang of this so that's awesome. The only thing that I want to mention is that we follow a style guide when programming so that our code is structrued uniformly throughout. For example, we format our if statements like this

if (condition)
{
    code to run
}

This link will explain what you need to know. https://github.com/UCSolarCarTeam/Development-Resources/tree/master/Development-Guide/Style-Guide

2021-02-27 21:31 UTC, DatLam25 commented
This looks good to me. Well done on finishing the training. Wait for another review before closing this PR.

2021-02-27 21:31 UTC, DatLam25 approved these changes

2021-02-27 22:27 UTC, Hesham-E requested changes
Looks good! (Whoops I meant to do this as an approve)

2021-02-27 22:28 UTC, Hesham-E approved these changes
There we go

2021-02-27 22:31 UTC, closed without merging