Completed Telemetry Teaser
UCSolarCarTeam/Development-Resources pull request #236
Opened 2021-10-30 18:01 UTC by brian-ngyn

2021-10-30 19:41 UTC, JensVarughese requested changes
Looks good so far, just a small change to formatting would be nice!

2021-10-30 19:41 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +  buttonPress = false;
I know some of the variables (weather, speed, and battery) were initialed with their declaration, but it is preferred to initialize the variables in the constructor.

Something like this:
![image](https://user-images.githubusercontent.com/29678619/139556332-2f49f11d-c7c4-44d1-a140-da70ef25c0bf.png)

2021-10-30 19:41 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
>  }
you should add an indent here. (right now its the same indentation as the line before)

2021-10-30 19:41 UTC, JensVarughese commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
>  import { Component, OnInit } from '@angular/core';
You don't need to import OnInit, as you didn't use it.

2021-10-30 20:05 UTC, JaydenBischoff requested changes
Looks great so far! I included a few suggestions in my comments.

2021-10-30 20:05 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +
Small syntax thing: This extra line can be removed.

2021-10-30 21:06 UTC, JensVarughese approved these changes
Looks good from what I see. Wait till Jayden approves this as well

2021-10-30 21:21 UTC, JaydenBischoff requested changes
I noticed that the error messages only show if the input field changes. For example, when the page first loads, if you click the "Calculate" button no error shows even though the speed and battery fields are empty. 
Can you fix this so that the error messages show in this case.

2021-10-30 21:28 UTC, Dillonsd reviewed
Good job! Comments are nit-picky but these kind of formatting conventions are checked by our CI tool and will fail the build.

2021-10-30 21:28 UTC, Dillonsd commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +    this.outputMessage = "";
We use ' for strings instead of ". Running ng lint will tell you about any formatted conventions.

2021-10-30 21:28 UTC, Dillonsd commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +};
You don't need a semi-colon at the end of a class in TS

2021-10-30 21:28 UTC, Dillonsd commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.ts
> +    this.outputMessage = "The predicted range of the Elysia is " + this.range + "km.";
Same thing, ' instead of "

2021-11-13 21:56 UTC, JaydenBischoff commented on Recruit-Training/Advanced-Recruit-Training/Telemetry-Teaser/src/app/app.component.html
> +      <label *ngIf="(speedInput.invalid && (speedInput.dirty || !speedInput.touched)) && this.buttonPress">
This fixes the problem where the error doesn't show when the inputs are untouched when the form is submitted but it introduces a new problem. Now if the user clicks on the input field but leaves it blank and submits the form, no error appears. 
There are probably a few ways to fix this but here is a hint for one way that follows what you did in this commit. Consider what your `ngIf` statement is saying. What can you add or change to check all cases?

2021-11-20 22:33 UTC, JaydenBischoff approved these changes
Great job! Seems to work in all cases that I tested. You can close this pr instead of merging it.

2021-11-20 22:40 UTC, closed without merging