User/muzman123/recruit training
UCSolarCarTeam/Development-Resources pull request #284
Opened 2022-10-22 17:10 UTC by muzman123

2022-10-22 17:31 UTC, JensVarughese requested changes
Looks good. Just a few styling fixes.

2022-10-22 17:31 UTC, JensVarughese commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +     cout <<"original value of y:"<<b <<endl;
Make sure your spacing is consistent. so it would be:
`cout << "original value of x:" << a << endl;`
`cout << "original value of y:" << b << endl;`

2022-10-22 17:31 UTC, JensVarughese commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +     cout <<"swapped value of y:" <<b <<endl;
same here

2022-10-29 21:45 UTC, DatLam25 commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +    *age_ = age;
You can replace these two lines with just: `age_ = new int(age);` to initialize age_ to a pointer pointing to age.

2022-10-29 21:45 UTC, DatLam25 commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +    *age_ = newAge;
you don't need to use `new int()` again here, `*age_ = newAge;` should be sufficient

2022-11-26 20:46 UTC, bryce-krispies requested changes
I've left some comments in your review - but still this is very good!
Re-request the review once you've made the changes.

2022-11-26 20:46 UTC, bryce-krispies commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +    int total_ = 0;
The post-fixed underscore is only for class variables.

Look to the [style guide](https://github.com/UCSolarCarTeam/Development-Resources/tree/master/Development-Guide/Style-Guide).

2022-11-26 20:46 UTC, bryce-krispies commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +    int oldAge = x.getAge();
Minor: You could just combine these three lines into a single line

`x.SetAge(x.getAge()++)`

2022-11-26 20:46 UTC, bryce-krispies commented on Recruit-Training/Basic-Recruit-Training/person/Person.cpp
> +Person::Person()
You should still allocate memory for age_

```
Person::Person()
{
  _age = new int();
}
```

Or better yet, you can do this:
`Person::Person(): age_(new int){}`

2022-11-26 20:46 UTC, bryce-krispies commented on Recruit-Training/Basic-Recruit-Training/person/main.cpp
> +    *x += 1;
Minor: We prefer `*x++`

2022-11-26 20:46 UTC, bryce-krispies commented on Recruit-Training/Basic-Recruit-Training/pointers/main.cpp
> +    mySwap(x, y);
This doesn't actually swap x and y.
If you print out x and y after line 44, you will see that x and y haven't changed.

2023-09-30 19:51 UTC, closed without merging